import os, re

files = [
    'single-software.php', 'archive-software.php', 'header.php', 'footer.php',
    'home.php', 'single.php', 'page-compare.php', 'page-login.php',
    'page-profile.php', 'page-register.php', 'page-reset-password.php',
    'page-categories.php', 'functions.php'
]
base_dir = r'd:\laragon\www\SoftZorUsa\wp-content\themes\softmir'

translations = {
    "скидку": "discount",
    "Введите новый пароль для вашего аккаунта": "Enter a new password for your account",
    "Копировать ссылку": "Copy link",
    "Программы для сравнения не найдены.": "No software found for comparison.",
    "Число": "Number",
    "Источник": "Source",
    "Ручное добавление": "Manual addition",
    "Скаут": "Scout",
    "проверенные": "verified",
    "Следующая": "Next",
    "Скриншот интерфейса %s": "Interface screenshot %s",
    "Удалить": "Delete",
    "Список": "List",
    "Emoji или CSS-класс иконки": "Emoji or CSS icon class",
    "Рекомендуемый продукт": "Recommended product",
    "Оставьте пустым, если не хотите менять пароль": "Leave blank if you don't want to change password",
    "Email или логин": "Email or username",
    "Некорректный email-адрес.": "Invalid email address.",
    "Сброс пароля": "Password Reset",
    "Личный кабинет": "Personal Cabinet",
    "Добавить категорию": "Add category",
    "Детали продукта": "Product Details",
    "Минимум 8 символов": "Minimum 8 characters",
    "Редактировать интегратора": "Edit integrator",
    "или": "or",
    "Верхнее меню (Header)": "Header menu",
    "Наши эксперты помогут с выбором и внедрением.": "Our experts will help with selection and implementation.",
    "Сохранить изменения": "Save changes",
    "заявок": "requests",
    "Скрыть": "Hide",
    "Политика конфиденциальности": "Privacy Policy",
    "Цена": "Price",
    "Отображаемое имя": "Display name",
    "Найдено:": "Found:",
    "Назад": "Back",
    "Далее": "Next",
    "Информация": "Information",
    "Добавить новый атрибут": "Add new attribute",
    "Забыли пароль?": "Forgot your password?",
    "Автор статей": "Article author",
    "Разрешить выбор нескольких значений": "Allow multiple selection",
    "Зарегистрируйтесь": "Register",
    "Искать": "Search",
    "заявка": "request",
    "Уже": "Already",
    "Новый пароль": "New password",
    "Погано": "Poor",
    "Search по категориям...": "Search categories...",
    "Редактировать профиль": "Edit profile",
    "Админ-панель": "Admin panel",
    "Категории": "Categories",
    "Добавить ПО": "Add Software",
    "Любой": "Any",
    "ПО": "Software",
    "Более свежие и подробные технические характеристики всегда смотрите на": "For more recent and detailed technical specifications, always refer to",
    "Скриншот 1": "Screenshot 1",
    "Скриншот 2": "Screenshot 2",
    "Скриншот 3": "Screenshot 3",
    "Скриншот 4": "Screenshot 4",
    "Участвует в фильтрации": "Participates in filtering",
    "Подтвердите пароль": "Confirm password",
    "Средне": "Average",
    "Программное обеспечение": "Software",
    "Відмінно": "Excellent",
    "Отлично": "Excellent",
    "Привязка Google": "Google binding",
    "Редактировать атрибут": "Edit attribute",
    "Скриншоты": "Screenshots",
    "Регистрируясь, вы принимаете %1$sУсловия использования%2$s и %3$sПолитику конфиденциальности%4$s.": "By registering, you accept the %1$sTerms of Use%2$s and %3$sPrivacy Policy%4$s.",
    "Сайт программы": "Software website",
    "Посетить сайт": "Visit website",
    "Сетка": "Grid",
    "Логин": "Login",
    "Отправить ссылку": "Send link",
    "Интегратор (Vendor)": "Integrator (Vendor)",
    "Множественный выбор": "Multiple choice",
    "Все источники": "All sources",
    "Дуже добре": "Very good",
    "Очень хорошо": "Very good",
    "Безопасно. Ни к чему не обязывает.": "Safe. No obligations.",
    "Нет аккаунта?": "No account?",
    "Добавить атрибут": "Add attribute",
    "Обзор": "Overview",
    "На модерации": "Pending review",
    "Почему это ТОП": "Why this is TOP",
    "Добавить к сравнению": "Add to comparison",
    "В сравнении": "In comparison",
    "Текст": "Text",
    "Продолжая, вы соглашаетесь с нашими Условиями использования и Политикой конфиденциальности.": "By continuing, you agree to our Terms of Use and Privacy Policy.",
    "Атрибут": "Attribute",
    "Цена (отображение в карточке)": "Price (display in card)",
    "Основная": "Main",
    "Редактировать ПО": "Edit Software",
    "Предыдущая": "Previous",
    "Да": "Yes",
    "Показать больше...": "Show more...",
    "Скидка": "Discount",
    "Чекбоксы": "Checkboxes",
    "Основная колонка": "Main column",
    "Category ПО": "Software Category",
    "логотип": "logo",
    "Плюсы и минусы": "Pros and cons",
    "Search ПО": "Search Software",
    "сайте производителя": "manufacturer's website",
    "Александр": "Alexander",
    "Плохо": "Poor",
    "Отправить письмо повторно": "Resend email",
    "Ваше имя": "Your name",
    "Нижнее меню (Footer)": "Footer menu",
    "Войти через Google": "Log in with Google",
    "Отзывы пользователей": "User reviews",
    "Повторите пароль": "Repeat password",
    "Ужасно": "Terrible",
    "Условия использования": "Terms of Use",
    "Например: От $19/мес": "Example: From $19/mo",
    "Оставьте заявку — мы выторгуем эксклюзивную цену у разработчика.": "Leave a request - we will negotiate an exclusive price from the developer.",
    "Расположение в карточке": "Position in card",
    "Будьте первым, кто оставит заявку!": "Be the first to leave a request!",
    "Новая заявка:": "New request:",
    "Сравнение %d программ": "Comparison of %d software",
    "Краткое описание": "Short description",
    "Все источники": "All sources",
    "Связаться": "Contact",
    "Дата регистрации": "Registration date",
    "Иконка": "Icon",
    "Атрибуты ещё не созданы.": "Attributes not created yet.",
    "Интегратор": "Integrator",
    "индивидуальную скидку": "individual discount",
    "Регистрация": "Registration",
    "Этот email уже подписан.": "This email is already subscribed.",
    "Логотип компании": "Company logo",
    "Настройки атрибута": "Attribute settings",
    "на модерации": "pending review",
    "Атрибуты ПО": "Software Attributes",
    "Категории ПО": "Software Categories",
    "Логотип": "Logo",
    "Программы не найдены": "Software not found",
    "Загрузка списка программ для сравнения...": "Loading list of software for comparison...",
    "Категория": "Category",
    "Данные интегратора": "Integrator data",
    "Таблица": "Table",
    "Видео (YouTube)": "Video (YouTube)",
    "Сбросить": "Reset",
    "Совет SoftZor:": "SoftZor tip:",
    "Похожие статьи": "Related articles",
    "Ссылка (URL)": "Link (URL)",
    "Оставьте заявку — мы договоримся <br>с вендором о партнерской цене.": "Leave a request - we will negotiate<br>a partner price with the vendor.",
    "Жахливо": "Terrible",
    "Попробовать %s бесплатно": "Try %s for free",
    "Зажмите Ctrl для множественного выбора": "Hold Ctrl for multiple selection",
    "Выпадающий список": "Dropdown list",
    "Добавить нового интегратора": "Add new integrator",
    "Оставить заявку": "Leave a request",
    "Добавить интегратора": "Add integrator",
    "Пароль": "Password",
    "Введите email для получения ссылки сброса": "Enter email to receive reset link",
    "Атрибуты не найдены": "Attributes not found",
    "Тип аккаунта": "Account type",
    "Средняя секция": "Middle section",
    "Создать аккаунт": "Create account",
    "Рейтинг": "Rating",
    "Ваш пароль": "Your password",
    "Показать пароль": "Show password",
    "Середньо": "Average",
    "Проверено:": "Verified:",
    "Дополнительные характеристики": "Additional features",
    "Описание": "Description",
    "Варианты": "Options",
    "Файлы Cookie & Affiliate": "Cookies & Affiliate files",
    "Установить новый пароль": "Set new password",
    "Имя пользователя": "Username",
    "Привязан": "Linked",
    "Выберите": "Select",
    "Войти": "Login",
    "Нюансы и Риски": "Nuances and Risks",
    "Запомнить меня": "Remember me",
    "Создайте атрибуты": "Create attributes",
    "Перейти в каталог": "Go to catalog",
    "Ссылки и Медиа": "Links and Media",
    "Создайте аккаунт для доступа к платформе": "Create an account to access the platform",
    "Зарегистрироваться через Google": "Register with Google",
    "Вернуться к входу": "Return to login",
    "Сохраните подборку для согласования: отправьте информацию об этом продукте себе на почту": "Save the selection for approval: send info about this product to your email",
    "Рекомендуемый размер 300x150": "Recommended size 300x150",
    "Не привязан": "Not linked",
    "Атрибуты": "Attributes",
    "Пока нет статей": "No articles yet",
    "Не найдено": "Not found",
    "Адрес электронной почты": "Email address",
    "Вам ПОДОЙДЁТ, если:": "Will SUIT you if:",
    "Не показывать": "Do not show",
    "Если ничего не выбрано — атрибут для всех категорий": "If nothing is selected - attribute for all categories",
    "Показывать в фильтрах каталога": "Show in catalog filters",
    "Основная информация (Логотип и Category)": "Basic info (Logo and Category)",
    "Меню": "Menu",
    "Найдите оптимальное решение для вашего бизнеса среди проверенных продуктов": "Find the optimal solution for your business among verified products",
    "Тип данных": "Data type",
    "Отправьте мне информацию": "Send me information",
    "Популярные статьи": "Popular articles",
    "Search категорий": "Search categories",
    "Содержание": "Table of contents",
    "Программы для сравнения не найдены.": "No software found for comparison.",
    "Меню пользователя": "User menu",
    "Все интеграторы": "All integrators",
    "Выберите основную категорию для хлебных крошек и подтягивания ключевых функций.": "Select primary category for breadcrumbs and key features.",
    "Изменить пароль": "Change password",
    "Подтвердите новый пароль": "Confirm new password",
    "Ключевые функции": "Key features",
    "Уже есть аккаунт?": "Already have an account?",
    "Главная": "Home",
    "Написать отзыв": "Write a review",
    "Отправить": "Send",
    "Отзывы": "Reviews",
    "Добавить новое ПО": "Add new software",
    "Все программы": "All software",
    "Интеграторы": "Integrators",
    "Все категории": "All categories",
    "Родительская категория": "Parent category",
    "Редактировать категорию": "Edit category",
    "Выйти": "Logout",
    "Совместная закупка": "Group Buying",
    "Похожие продукты": "Similar products",
    "Навигация": "Navigation",
    "Каталог": "Catalog",
    "Сравнение": "Comparison",
    "Оставить отзыв": "Leave a review",
    "Пользователь %s оставил заявку через CTA-форму на сайте.": "User %s left a request via CTA form on the site.",
    "Лучше не брать, если:": "Better avoid if:",
    "Сайдбар": "Sidebar",
    "Видео-обзор": "Video review",
    "Через запятую. Только для типов «Выпадающий список» и «Чекбоксы»": "Comma separated. Only for Dropdown and Checkboxes types",
    "Emoji или CSS-класс, напр. 🌐": "Emoji or CSS class, e.g. 🌐",
    "Привязка к категориям": "Binding to categories",
    "Расположение на странице": "Position on page",
    "Сравнить": "Compare",
    "Сравнить (%d)": "Compare (%d)",
    "Добавлено к сравнению": "Added to comparison",
    "Перейти к сравнению": "Go to comparison",
    "Показывать только отличия": "Show only differences",
    "Скрыть отличия": "Hide differences",
    "Добавить к сравнению": "Add to comparison",
    "Убрать из сравнения": "Remove from comparison",
    "Некорректный email.": "Invalid email.",
    "Пароли не совпадают.": "Passwords do not match.",
    "Сбросить пароль": "Reset password",
    "Надіслати": "Send",
    "Зберегти": "Save",
    "Вхід": "Login",
    "Тип": "Type",
    "Карточка": "Card",
    "Страница": "Page",
    "Ссылка": "Link",
    "Средняя": "Middle",
    "Подвал": "Footer",
    "Написать відгук": "Write a review",
    "Написати відгук": "Write a review",
    "Проверено": "Verified",
    "На модерации — ещё не проверено администратором": "Pending review - not verified by admin",
    "Все": "All",
    "просмотры": "views",
    "просмотров": "views",
    "просмотра": "views",
    "Найти": "Find",
    "Категория": "Category",
    "Искать программы": "Search software",
    "Search атрибутов": "Search attributes",
    "Search ПО": "Search Software",
    "Search...": "Search...",
    "Результаты поиска:": "Search results:",
    "Сбросить все фильтры": "Reset all filters",
    "Программы": "Software",
    "Программа": "Software",
    "Сайт": "Website",
    "отзывов": "reviews",
    "отзыва": "reviews",
    "отзыв": "review",
    "Загрузка...": "Loading...",
    "Ошибка": "Error",
    "Успешно": "Success",
    "Удалить аккаунт": "Delete account",
    "Настройки": "Settings",
    "Профиль": "Profile",
    "Сообщения": "Messages",
    "Уведомления": "Notifications",
    "Поддержка": "Support",
    "Контакты": "Contacts",
    "О нас": "About us",
    "Блог": "Blog",
    "Статьи": "Articles",
    "Читать далее": "Read more",
    "Опубликовано:": "Published:",
    "Автор:": "Author:",
    "Теги:": "Tags:",
    "Категории:": "Categories:",
    "Поделиться:": "Share:",
    "Поиск": "Search",
    "Отмена": "Cancel",
    "Закрыть": "Close",
    "Принять": "Accept",
    "Отклонить": "Decline",
    "Подробнее": "More info",
    "Смотреть все": "View all",
    "Загрузить еще": "Load more",
    "Нет данных": "No data",
    "Неизвестно": "Unknown",
    "Да": "Yes",
    "Нет": "No",
    "Вкл": "On",
    "Выкл": "Off",
    "Активен": "Active",
    "Неактивен": "Inactive",
    "Ожидание": "Pending",
    "Завершено": "Completed",
    "Отменено": "Cancelled",
    "Новый": "New",
    "Старый": "Old",
    "Лучший": "Best",
    "Популярный": "Popular",
    "Рекомендуемый": "Recommended",
    "Бесплатно": "Free",
    "Платно": "Paid",
    "От": "From",
    "До": "To",
    "В месяц": "Per month",
    "В год": "Per year",
    "Единоразово": "One-time",
    "Тарифы": "Pricing",
    "Характеристики": "Features",
    "Преимущества": "Advantages",
    "Недостатки": "Disadvantages",
    "Интеграции": "Integrations",
    "Платформы": "Platforms",
    "Языки": "Languages",
    "Поддержка:": "Support:",
    "Обучение:": "Training:",
    "Развертывание:": "Deployment:",
    "Скриншот": "Screenshot",
    "Видео": "Video",
    "Фото": "Photo",
    "Изображение": "Image",
    "Файл": "File",
    "Документ": "Document",
    "Ссылка:": "Link:",
    "Размер:": "Size:",
    "Дата:": "Date:",
    "Время:": "Time:",
    "Количество:": "Amount:",
    "Сумма:": "Total:",
    "Итого:": "Total:",
    "Все права защищены.": "All rights reserved.",
    "Разработано": "Developed by",
    "Дизайн": "Design by",
    "Код": "Code by",
    "Сделано с любовью": "Made with love",
    "Пожалуйста, подождите...": "Please wait...",
    "Ошибка сервера.": "Server error.",
    "Неверный логин или пароль.": "Invalid login or password.",
    "Пользователь с таким email уже существует.": "User with this email already exists.",
    "Пароль должен содержать минимум 8 символов.": "Password must contain at least 8 characters.",
    "Письмо со ссылкой для сброса пароля отправлено на ваш email.": "An email with a password reset link has been sent to your email address.",
    "Ссылка недействительна или устарела.": "The link is invalid or expired.",
    "Пароль успешно изменен.": "Password successfully changed.",
    "Ваш аккаунт успешно создан.": "Your account has been successfully created.",
    "Профиль успешно обновлен.": "Profile successfully updated.",
    "Продукт успешно добавлен.": "Product successfully added.",
    "Продукт успешно обновлен.": "Product successfully updated.",
    "Продукт успешно удален.": "Product successfully deleted.",
    "Отзыв успешно отправлен.": "Review successfully submitted.",
    "Спасибо за ваш отзыв!": "Thank you for your review!",
    "Ваша заявка принята.": "Your request has been accepted.",
    "Мы свяжемся с вами в ближайшее время.": "We will contact you shortly.",
    "Подписка успешно оформлена.": "Subscription successfully completed.",
    "Вы успешно отписались.": "You have successfully unsubscribed.",
    "Файл слишком большой.": "File is too large.",
    "Недопустимый формат файла.": "Invalid file format.",
    "Пожалуйста, заполните все обязательные поля.": "Please fill in all required fields.",
    "Ошибка при отправке письма.": "Error sending email.",
    "Пожалуйста, подтвердите, что вы не робот.": "Please confirm you are not a robot.",
    "Слишком много попыток. Пожалуйста, попробуйте позже.": "Too many attempts. Please try again later.",
    "Доступ запрещен.": "Access denied.",
    "У вас нет прав для выполнения этого действия.": "You do not have permission to perform this action.",
    "Только для зарегистрированных пользователей.": "For registered users only.",
    "Пожалуйста, авторизуйтесь.": "Please log in.",
    "Сессия истекла.": "Session expired.",
    "Обновите страницу.": "Refresh the page.",
    "Что-то пошло не так.": "Something went wrong.",
    "Неизвестная ошибка.": "Unknown error.",
    "Пожалуйста, обратитесь в службу поддержки.": "Please contact support.",
    "Помощь": "Help",
    "FAQ": "FAQ",
    "Частые вопросы": "Frequently asked questions",
    "Задать вопрос": "Ask a question",
    "Служба поддержки": "Customer support",
    "Техническая поддержка": "Technical support",
    "Отдел продаж": "Sales department",
    "Партнерская программа": "Affiliate program",
    "Для партнеров": "For partners",
    "Для разработчиков": "For developers",
    "Для инвесторов": "For investors",
    "Для прессы": "For press",
    "Карьера": "Careers",
    "Вакансии": "Vacancies",
    "Наша команда": "Our team",
    "История компании": "Company history",
    "Миссия и ценности": "Mission and values",
    "Реквизиты": "Company details",
    "Адрес:": "Address:",
    "Телефон:": "Phone:",
    "Режим работы:": "Working hours:",
    "Пн-Пт:": "Mon-Fri:",
    "Сб-Вс:": "Sat-Sun:",
    "Без выходных": "No days off",
    "Круглосуточно": "24/7",
    "Онлайн": "Online",
    "Офлайн": "Offline",
    "Доставка": "Delivery",
    "Оплата": "Payment",
    "Гарантия": "Warranty",
    "Возврат": "Return",
    "Условия": "Terms",
    "Правила": "Rules",
    "Соглашение": "Agreement",
    "Договор": "Contract",
    "Оферта": "Offer",
    "Лицензия": "License",
    "Сертификаты": "Certificates",
    "Документация": "Documentation",
    "Руководство": "Manual",
    "Инструкция": "Instruction",
    "Скачать": "Download",
    "Установить": "Install",
    "Обновить": "Update",
    "Версия:": "Version:",
    "Размер файла:": "File size:",
    "Системные требования:": "System requirements:",
    "ОС:": "OS:",
    "Процессор:": "Processor:",
    "Память:": "Memory:",
    "Место на диске:": "Disk space:",
    "Видеокарта:": "Video card:",
    "Сеть:": "Network:",
    "Интернет-соединение:": "Internet connection:",
    "Браузер:": "Browser:",
    "Устройства:": "Devices:",
    "ПК": "PC",
    "Mac": "Mac",
    "Linux": "Linux",
    "iOS": "iOS",
    "Android": "Android",
    "Смартфон": "Smartphone",
    "Планшет": "Tablet",
    "Веб": "Web",
    "Облако": "Cloud",
    "SaaS": "SaaS",
    "On-premise": "On-premise",
    "Открытый исходный код": "Open source",
    "Проприетарное": "Proprietary",
    "Бесплатная пробная версия": "Free trial",
    "Демо": "Demo",
    "Запросить демо": "Request demo",
    "Связаться с отделом продаж": "Contact sales",
    "Купить": "Buy",
    "Заказать": "Order",
    "Оформить подписку": "Get subscription",
    "Перейти к оплате": "Proceed to payment",
    "Добавить в корзину": "Add to cart",
    "В корзине": "In cart",
    "Оформить заказ": "Place order",
    "Продолжить покупки": "Continue shopping",
    "Ваша корзина пуста": "Your cart is empty",
    "Итого к оплате:": "Total to pay:",
    "Скидка:": "Discount:",
    "Промокод:": "Promo code:",
    "Применить": "Apply",
    "Промокод успешно применен.": "Promo code successfully applied.",
    "Недействительный промокод.": "Invalid promo code.",
    "Метод оплаты:": "Payment method:",
    "Карта": "Card",
    "Наличные": "Cash",
    "Безналичный расчет": "Bank transfer",
    "Электронные деньги": "E-money",
    "Криптовалюта": "Cryptocurrency",
    "Статус оплаты:": "Payment status:",
    "Оплачено": "Paid",
    "Не оплачено": "Not paid",
    "Ожидает оплаты": "Awaiting payment",
    "Ошибка оплаты": "Payment error",
    "История заказов": "Order history",
    "Мои заказы": "My orders",
    "Мои подписки": "My subscriptions",
    "Мои файлы": "My files",
    "Мои курсы": "My courses",
    "Мои сертификаты": "My certificates",
    "Мои достижения": "My achievements",
    "Мои настройки": "My settings",
    "Избранное": "Favorites",
    "Добавить в избранное": "Add to favorites",
    "Удалить из избранного": "Remove from favorites",
    "Сортировать по:": "Sort by:",
    "Цене (по возрастанию)": "Price (low to high)",
    "Цене (по убыванию)": "Price (high to low)",
    "Рейтингу": "Rating",
    "Популярности": "Popularity",
    "Дате": "Date",
    "Названию (А-Я)": "Name (A-Z)",
    "Названию (Я-А)": "Name (Z-A)",
    "Показывать по:": "Show per page:",
    "Вид:": "View:",
    "Сбросить фильтры": "Reset filters",
    "Применить фильтры": "Apply filters",
    "Цена от": "Price from",
    "Цена до": "Price to",
    "Оценка от": "Rating from",
    "Оценка до": "Rating to",
    "Бренд": "Brand",
    "Производитель": "Manufacturer",
    "Страна": "Country",
    "Город": "City",
    "Язык": "Language",
    "Валюта": "Currency",
    "Тема": "Theme",
    "Светлая": "Light",
    "Темная": "Dark",
    "Системная": "System",
    "Уведомления на email": "Email notifications",
    "Push-уведомления": "Push notifications",
    "СМС-уведомления": "SMS notifications",
    "Новостная рассылка": "Newsletter",
    "Акции и скидки": "Promotions and discounts",
    "Обновления системы": "System updates",
    "Безопасность": "Security",
    "Двухфакторная аутентификация": "Two-factor authentication",
    "Сменить пароль": "Change password",
    "Вы уверены?": "Are you sure?",
    "Это действие нельзя отменить.": "This action cannot be undone.",
    "Да, удалить": "Yes, delete",
    "Нет, отменить": "No, cancel",
    "Копировать": "Copy",
    "Вставить": "Paste",
    "Вырезать": "Cut",
    "Выделить все": "Select all",
    "Отменить действие": "Undo",
    "Повторить действие": "Redo",
    "Печать": "Print",
    "Скачать PDF": "Download PDF",
    "Экспорт": "Export",
    "Импорт": "Import",
    "Загрузить": "Upload",
    "Открыть": "Open",
    "Развернуть": "Expand",
    "Свернуть": "Collapse",
    "Следующий": "Next",
    "Предыдущий": "Previous",
    "Первый": "First",
    "Последний": "Last",
    "Вверх": "Up",
    "Вниз": "Down",
    "Вперед": "Forward",
    "Перезагрузить": "Reload",
    "Лайк": "Like",
    "Дизлайк": "Dislike",
    "Комментировать": "Comment",
    "Ответить": "Reply",
    "Жалоба": "Report",
    "Заблокировать": "Block",
    "Разблокировать": "Unblock",
    "Отписаться": "Unfollow",
    "В друзья": "Add friend",
    "Из друзей": "Remove friend",
    "Сообщение": "Message",
    "Позвонить": "Call",
    "Видеозвонок": "Video call",
    "Не беспокоить": "Do not disturb",
    "Отошел": "Away",
    "Невидимка": "Invisible",
    "О себе": "About me",
    "Дата рождения": "Date of birth",
    "Пол": "Gender",
    "Мужской": "Male",
    "Женский": "Female",
    "Другой": "Other",
    "Не указан": "Not specified",
    "Образование": "Education",
    "Работа": "Work",
    "Интересы": "Interests",
    "Веб-сайт": "Website",
    "Социальные сети": "Social networks",
    "Домашняя страница": "Homepage",
}

for file_name in files:
    path = os.path.join(base_dir, file_name)
    if not os.path.exists(path):
        continue
    
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Custom replacements for PHP files
    # Replace dictionary strings first
    for ru, en in translations.items():
        content = content.replace(ru, en)

    # Some missed strings that are hardcoded
    content = content.replace('📋 Атрибуты ПО', '📋 Software Attributes')
    content = content.replace('Атрибуты ПО', 'Software Attributes')
    content = content.replace('📦 Источник', '📦 Source')
    content = content.replace('🤖 Скаут ✅', '🤖 Scout ✅')
    content = content.replace('🤖 Скаут ⚠️', '🤖 Scout ⚠️')
    content = content.replace('🤖 Скаут', '🤖 Scout')
    content = content.replace('⚠️ На модерации', '⚠️ Pending review')
    content = content.replace('✍️ Ручное добавление', '✍️ Manual addition')
    content = content.replace('Выпадающий список', 'Dropdown list')
    content = content.replace('🚀 Вам ПОДОЙДЁТ, если:', '🚀 Will SUIT you if:')
    content = content.replace('Сбросить все фильтры', 'Reset all filters')

    # Save
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
