name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Theme (SoftMir)
            local_dir: ./wp-content/themes/softmir/
            server_dir: public_html/wp-content/themes/softmir/
            state_name: .ftp-deploy-sync-state-theme.json
          - name: MU Plugins
            local_dir: ./wp-content/mu-plugins/
            server_dir: public_html/wp-content/mu-plugins/
            state_name: .ftp-deploy-sync-state-muplugins.json
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ matrix.local_dir }}
          server-dir: ${{ matrix.server_dir }}
          state-name: ${{ matrix.state_name }}
          dangerous-clean-slate: false
